version: "3"

services:
  server:
    build: .
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend
    
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongodb: